alias s='cd ..'
alias cl='clear'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias ll='ls -lAF'
alias distupgrade='sudo apt-get dist-upgrade'
alias upgrade='sudo apt-get upgrade'
alias update='sudo apt-get update'
